import type { FieldSchema } from "@/lib/cms-types";

export type CollectionMode = "list" | "singleton" | "nested";

export type CollectionDef = {
  key: string;
  label: string;
  description: string;
  endpoint: string;
  mode: CollectionMode;
  nestedKey?: string;
  nestedParent?: Record<string, unknown>;
  titleField: string;
  fields: FieldSchema[];
  defaults: Record<string, unknown>;
  deleteVia?: "json" | "query";
  putIdKey?: "id" | "_id";
  createMethod?: "POST" | "PUT";
  replaceList?: boolean;
  readOnly?: boolean;
};

export const COLLECTIONS: Record<string, CollectionDef> = {
  notices: {
    key: "notices",
    label: "Notices",
    description: "Home notice board, news, and announcements.",
    endpoint: "/api/admin/notices",
    mode: "list",
    titleField: "title",
    defaults: { title: "", subject: "", body: "", category: "News & Circulars", isNew: true, link: "" },
    fields: [
      { key: "title", label: "Title", type: "string" },
      { key: "subject", label: "Subject", type: "string" },
      { key: "body", label: "Body", type: "text" },
      { key: "refNo", label: "Ref no", type: "string" },
      {
        key: "category",
        label: "Category",
        type: "select",
        options: [
          { value: "News & Circulars", label: "News & Circulars" },
          { value: "Announcements", label: "Announcements" },
          { value: "Admission", label: "Admission" },
          { value: "School Rules", label: "School Rules" },
        ],
      },
      { key: "link", label: "Link", type: "url" },
      { key: "isNew", label: "Mark as new", type: "boolean" },
    ],
  },
  events: {
    key: "events",
    label: "Events",
    description: "Upcoming events on the home page.",
    endpoint: "/api/admin/events",
    mode: "list",
    titleField: "title",
    defaults: { title: "", description: "", imageUrl: "" },
    fields: [
      { key: "title", label: "Title", type: "string" },
      { key: "description", label: "Description", type: "text" },
      { key: "imageUrl", label: "Image", type: "image" },
      { key: "date", label: "Date", type: "string", placeholder: "YYYY-MM-DD" },
    ],
  },
  contacts: {
    key: "contacts",
    label: "Important contacts",
    description: "Contact page department numbers.",
    endpoint: "/api/admin/important-contacts?all=true",
    mode: "list",
    titleField: "department",
    defaults: { department: "", contactName: "", designation: "", phone: "", email: "", sortOrder: 0, isActive: true },
    fields: [
      { key: "department", label: "Department", type: "string" },
      { key: "contactName", label: "Name", type: "string" },
      { key: "designation", label: "Designation", type: "string" },
      { key: "phone", label: "Phone", type: "string" },
      { key: "email", label: "Email", type: "string" },
      { key: "sortOrder", label: "Order", type: "number" },
      { key: "isActive", label: "Active", type: "boolean" },
    ],
  },
  leadership: {
    key: "leadership",
    label: "Leadership / faculty",
    description: "Management and leadership member cards.",
    endpoint: "/api/admin/leadership",
    mode: "list",
    titleField: "name",
    defaults: { name: "", designation: "", image: "", sortOrder: 0 },
    fields: [
      { key: "name", label: "Name", type: "string" },
      { key: "designation", label: "Designation", type: "string" },
      { key: "image", label: "Photo", type: "image" },
      { key: "sortOrder", label: "Order", type: "number" },
    ],
  },
  teachers: {
    key: "teachers",
    label: "Academic excellence team",
    description: "Managing committee roster from teacher.txt.",
    endpoint: "/api/admin/teachers",
    mode: "list",
    titleField: "name",
    replaceList: true,
    defaults: { name: "", designation: "" },
    fields: [
      { key: "name", label: "Name", type: "string" },
      { key: "designation", label: "Designation", type: "string" },
    ],
  },
  blogs: {
    key: "blogs",
    label: "Blog posts",
    description: "School blog articles.",
    endpoint: "/api/blogs?admin=true",
    mode: "list",
    titleField: "title",
    defaults: { title: "", slug: "", excerpt: "", content: "", image: "", author: "Admin", status: "Published" },
    fields: [
      { key: "title", label: "Title", type: "string" },
      { key: "slug", label: "Slug", type: "string" },
      { key: "excerpt", label: "Excerpt", type: "text" },
      { key: "content", label: "Content", type: "text" },
      { key: "image", label: "Image", type: "image" },
      { key: "author", label: "Author", type: "string" },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "Published", label: "Published" },
          { value: "Draft", label: "Draft" },
        ],
      },
    ],
  },
  careers: {
    key: "careers",
    label: "Job openings",
    description: "Careers page listings.",
    endpoint: "/api/admin/career",
    mode: "list",
    titleField: "title",
    defaults: { title: "", department: "", experience: "", qualification: "", description: "", salary: "As per school norms", isActive: true, sortOrder: 0 },
    fields: [
      { key: "title", label: "Title", type: "string" },
      { key: "department", label: "Department", type: "string" },
      { key: "experience", label: "Experience", type: "string" },
      { key: "qualification", label: "Qualification", type: "string" },
      { key: "description", label: "Description", type: "text" },
      { key: "salary", label: "Salary", type: "string" },
      { key: "requirements", label: "Requirements", type: "csv" },
      { key: "isActive", label: "Active", type: "boolean" },
      { key: "sortOrder", label: "Order", type: "number" },
    ],
  },
  magazines: {
    key: "magazines",
    label: "Magazines",
    description: "School magazines and PDFs.",
    endpoint: "/api/admin/magazine",
    mode: "list",
    titleField: "name",
    defaults: { name: "", pdfUrl: "", year: new Date().getFullYear(), month: "January" },
    fields: [
      { key: "name", label: "Name", type: "string" },
      { key: "pdfUrl", label: "PDF", type: "url" },
      { key: "year", label: "Year", type: "number" },
      { key: "month", label: "Month", type: "string" },
    ],
  },
  downloads: {
    key: "downloads",
    label: "Downloads",
    description: "Forms and prospectus PDFs.",
    endpoint: "/api/admin/downloads",
    mode: "list",
    titleField: "title",
    defaults: { title: "", description: "", filename: "", fileSize: "", pdfUrl: "" },
    fields: [
      { key: "title", label: "Title", type: "string" },
      { key: "description", label: "Description", type: "text" },
      { key: "filename", label: "Filename", type: "string" },
      { key: "fileSize", label: "File size", type: "string" },
      { key: "pdfUrl", label: "PDF URL", type: "url" },
    ],
  },
  galleries: {
    key: "galleries",
    label: "Photo galleries",
    description: "Photo gallery albums.",
    endpoint: "/api/admin/galleries",
    mode: "list",
    titleField: "title",
    putIdKey: "_id",
    deleteVia: "query",
    defaults: { title: "", page: "home", category: "Campus", description: "", cover: "", photos: [], featured: false },
    fields: [
      { key: "title", label: "Title", type: "string" },
      { key: "page", label: "Page", type: "string" },
      { key: "category", label: "Category", type: "string" },
      { key: "description", label: "Description", type: "text" },
      { key: "cover", label: "Cover image", type: "image" },
      { key: "photos", label: "Photo URLs", type: "csv" },
      { key: "featured", label: "Featured", type: "boolean" },
    ],
  },
  videos: {
    key: "videos",
    label: "Videos & media",
    description: "Video gallery and campus media items.",
    endpoint: "/api/admin/media-items",
    mode: "list",
    titleField: "title",
    defaults: { title: "", src: "", alt: "", type: "video", category: "Others" },
    fields: [
      { key: "title", label: "Title", type: "string" },
      { key: "src", label: "Source URL", type: "url" },
      { key: "alt", label: "Alt text", type: "string" },
      { key: "type", label: "Type", type: "string", placeholder: "photo, video, highlight" },
      { key: "category", label: "Category", type: "string" },
    ],
  },
  "hostel-facilities": {
    key: "hostel-facilities",
    label: "Hostel facilities",
    description: "Hostel page facility cards.",
    endpoint: "/api/hostel?type=facilities",
    mode: "list",
    titleField: "name",
    defaults: { name: "", description: "", src: "", sortOrder: 0 },
    fields: [
      { key: "name", label: "Name", type: "string" },
      { key: "description", label: "Description", type: "text" },
      { key: "src", label: "Image", type: "image" },
      { key: "sortOrder", label: "Order", type: "number" },
    ],
  },
  "hostel-fees": {
    key: "hostel-fees",
    label: "Hostel fees",
    description: "Hostel fee table.",
    endpoint: "/api/hostel?type=fees",
    mode: "list",
    titleField: "classLevel",
    defaults: { classLevel: "", nonAcFee: "", acFee: "", sortOrder: 0 },
    fields: [
      { key: "classLevel", label: "Class level", type: "string" },
      { key: "nonAcFee", label: "Non-AC fee", type: "string" },
      { key: "acFee", label: "AC fee", type: "string" },
      { key: "sortOrder", label: "Order", type: "number" },
    ],
  },
  "hostel-rules": {
    key: "hostel-rules",
    label: "Hostel rules",
    description: "Hostel guidelines.",
    endpoint: "/api/hostel?type=rules",
    mode: "list",
    titleField: "title",
    defaults: { category: "", title: "", bullets: [], sortOrder: 0 },
    fields: [
      { key: "category", label: "Category", type: "string" },
      { key: "title", label: "Title", type: "string" },
      { key: "bullets", label: "Bullets", type: "csv" },
      { key: "sortOrder", label: "Order", type: "number" },
    ],
  },
  transport: {
    key: "transport",
    label: "Bus routes",
    description: "Transport page routes.",
    endpoint: "/api/admin/transport",
    mode: "list",
    titleField: "routeNo",
    defaults: { routeNo: "", driver: "", phone: "", timing: "", stops: [] },
    fields: [
      { key: "routeNo", label: "Route no", type: "string" },
      { key: "driver", label: "Driver", type: "string" },
      { key: "phone", label: "Phone", type: "string" },
      { key: "timing", label: "Timing", type: "string" },
      { key: "stops", label: "Stops", type: "csv" },
    ],
  },
  holidays: {
    key: "holidays",
    label: "Holiday list",
    description: "Holiday calendar PDF.",
    endpoint: "/api/admin/holidays",
    mode: "singleton",
    createMethod: "POST",
    titleField: "title",
    defaults: { title: "Holiday List", pdfUrl: "" },
    fields: [
      { key: "title", label: "Title", type: "string" },
      { key: "pdfUrl", label: "PDF URL", type: "url" },
    ],
  },
  disclosures: {
    key: "disclosures",
    label: "CBSE disclosures",
    description: "Mandatory public disclosure documents.",
    endpoint: "/api/admin/disclosures",
    mode: "list",
    titleField: "title",
    defaults: { title: "", category: "documents", pdfUrl: "", value: "", details: "" },
    fields: [
      { key: "title", label: "Title", type: "string" },
      { key: "category", label: "Category", type: "string" },
      { key: "pdfUrl", label: "PDF URL", type: "url" },
      { key: "value", label: "Value", type: "string" },
      { key: "details", label: "Details", type: "text" },
    ],
  },
  cabinet: {
    key: "cabinet",
    label: "Investiture cabinet",
    description: "Student cabinet members.",
    endpoint: "/api/admin/cabinet",
    mode: "list",
    titleField: "name",
    defaults: { name: "", role: "", image: "", sortOrder: 0 },
    fields: [
      { key: "name", label: "Name", type: "string" },
      { key: "role", label: "Role", type: "string" },
      { key: "image", label: "Photo", type: "image" },
      { key: "sortOrder", label: "Order", type: "number" },
    ],
  },
  "pre-primary": {
    key: "pre-primary",
    label: "Pre-primary showcase",
    description: "Pre-primary photos and captions.",
    endpoint: "/api/pre-primary",
    mode: "list",
    titleField: "title",
    defaults: { section: "Pre School", title: "", description: "", src: "", alt: "", sortOrder: 0 },
    fields: [
      { key: "section", label: "Section", type: "string" },
      { key: "title", label: "Title", type: "string" },
      { key: "description", label: "Description", type: "text" },
      { key: "src", label: "Image", type: "image" },
      { key: "alt", label: "Alt text", type: "string" },
      { key: "sortOrder", label: "Order", type: "number" },
    ],
  },
  alumni: {
    key: "alumni",
    label: "Alumni registrations",
    description: "Submitted alumni forms.",
    endpoint: "/api/admin/alumni",
    mode: "list",
    titleField: "fullName",
    defaults: {
      fullName: "",
      parentsName: "",
      dateOfBirth: "",
      mobileNumber: "",
      emailId: "",
      permanentAddress: "",
      classCompleted: "",
      passingYear: "",
    },
    fields: [
      { key: "fullName", label: "Full name", type: "string" },
      { key: "parentsName", label: "Parent name", type: "string" },
      { key: "dateOfBirth", label: "Date of birth", type: "string" },
      { key: "mobileNumber", label: "Mobile", type: "string" },
      { key: "emailId", label: "Email", type: "string" },
      { key: "permanentAddress", label: "Address", type: "text" },
      { key: "classCompleted", label: "Class completed", type: "string" },
      { key: "passingYear", label: "Passing year", type: "string" },
    ],
  },
  inquiries: {
    key: "inquiries",
    label: "Admission inquiries",
    description: "Admission query submissions.",
    endpoint: "/api/admin/inquiries",
    mode: "list",
    titleField: "parentName",
    defaults: { parentName: "", studentName: "", contactNo: "", emailId: "", classApplied: "" },
    fields: [
      { key: "parentName", label: "Parent", type: "string" },
      { key: "studentName", label: "Student", type: "string" },
      { key: "contactNo", label: "Contact", type: "string" },
      { key: "emailId", label: "Email", type: "string" },
      { key: "classApplied", label: "Class", type: "string" },
      { key: "status", label: "Status", type: "string" },
      { key: "notes", label: "Notes", type: "text" },
    ],
  },
  results: {
    key: "results",
    label: "Board results",
    description: "Result years, toppers, and student lists.",
    endpoint: "/api/admin/results",
    mode: "list",
    titleField: "year",
    defaults: { year: "", title: "", passPercentage: "100%", highestScore: "", toppers: [], students: [], images: [] },
    fields: [
      { key: "year", label: "Year", type: "string", placeholder: "2024-25" },
      { key: "title", label: "Title", type: "string" },
      { key: "passPercentage", label: "Pass %", type: "string" },
      { key: "highestScore", label: "Highest score", type: "string" },
      { key: "highestScoreScorer", label: "Top scorer", type: "string" },
      { key: "distinctionsCount", label: "Distinctions", type: "number" },
      { key: "batchAverage", label: "Batch average", type: "string" },
      { key: "toppers", label: "Toppers JSON", type: "json" },
      { key: "students", label: "Students JSON", type: "json" },
      { key: "images", label: "Images JSON", type: "json" },
    ],
  },
  "carousel-home": {
    key: "carousel-home",
    label: "Home intro carousel",
    description: "Intro section slides on the home page.",
    endpoint: "/api/admin/carousel?key=homepage",
    mode: "nested",
    nestedKey: "slides",
    nestedParent: { key: "homepage" },
    titleField: "title",
    createMethod: "PUT",
    defaults: { image: "", title: "", description: "" },
    fields: [
      { key: "image", label: "Image", type: "image" },
      { key: "title", label: "Title", type: "string" },
      { key: "description", label: "Description", type: "text" },
    ],
  },
  "carousel-hero": {
    key: "carousel-hero",
    label: "Home hero slides",
    description: "Main hero banners.",
    endpoint: "/api/admin/carousel?key=hero",
    mode: "nested",
    nestedKey: "slides",
    nestedParent: { key: "hero" },
    titleField: "title",
    createMethod: "PUT",
    defaults: { image: "", subtitle: "", title: "", highlight: "", description: "" },
    fields: [
      { key: "image", label: "Image", type: "image" },
      { key: "subtitle", label: "Subtitle", type: "string" },
      { key: "title", label: "Title", type: "string" },
      { key: "highlight", label: "Highlight", type: "string" },
      { key: "description", label: "Description", type: "text" },
    ],
  },
  categories: {
    key: "categories",
    label: "Category / facility tiles",
    description: "Home and About LPS image tiles.",
    endpoint: "/api/admin/categories",
    mode: "nested",
    nestedKey: "items",
    nestedParent: { key: "homepage" },
    titleField: "title",
    createMethod: "PUT",
    defaults: { title: "", image: "", link: "#" },
    fields: [
      { key: "title", label: "Title", type: "string" },
      { key: "image", label: "Image", type: "image" },
      { key: "link", label: "Link", type: "url" },
    ],
  },
  brand: {
    key: "brand",
    label: "Brand assets",
    description: "Logo and favicon used in the navbar.",
    endpoint: "/api/admin/brand",
    mode: "list",
    titleField: "key",
    createMethod: "POST",
    defaults: { key: "logo", value: "", alt: "" },
    fields: [
      { key: "key", label: "Key", type: "string", placeholder: "logo, favicon" },
      { key: "value", label: "Image", type: "image" },
      { key: "alt", label: "Alt text", type: "string" },
    ],
  },
  "about-pages": {
    key: "about-pages",
    label: "About message pages",
    description: "Trust, principal, CEO, secretary, and management copy.",
    endpoint: "/api/admin/about-pages",
    mode: "list",
    titleField: "pageTitle",
    createMethod: "PUT",
    putIdKey: "slug" as unknown as "id",
    defaults: { slug: "", pageTitle: "", pageSubtitle: "", bannerImage: "", portraitImage: "", personName: "", personDesignation: "", content: "", inspirationContent: "" },
    fields: [
      { key: "slug", label: "Slug", type: "string" },
      { key: "pageTitle", label: "Page title", type: "string" },
      { key: "pageSubtitle", label: "Subtitle", type: "string" },
      { key: "bannerImage", label: "Banner", type: "image" },
      { key: "portraitImage", label: "Portrait", type: "image" },
      { key: "personName", label: "Person name", type: "string" },
      { key: "personDesignation", label: "Designation", type: "string" },
      { key: "content", label: "Content HTML", type: "text" },
      { key: "inspirationContent", label: "Inspiration HTML", type: "text" },
      { key: "members", label: "Members JSON", type: "json" },
    ],
  },
  sports: {
    key: "sports",
    label: "Sports page",
    description: "Players, games, and stats on the sports page.",
    endpoint: "/api/admin/sports",
    mode: "singleton",
    createMethod: "PUT",
    titleField: "key",
    defaults: { key: "main", complexImages: [], players: [], games: [], stats: [] },
    fields: [
      { key: "complexImages", label: "Complex images", type: "csv" },
      { key: "players", label: "Players JSON", type: "json" },
      { key: "games", label: "Games JSON", type: "json" },
      { key: "stats", label: "Stats JSON", type: "json" },
    ],
  },
  "page-contents": {
    key: "page-contents",
    label: "Page Content Sections",
    description: "Database content and sections for all website pages.",
    endpoint: "/api/admin/pages",
    mode: "list",
    titleField: "title",
    createMethod: "PUT",
    putIdKey: "slug" as unknown as "id",
    defaults: { slug: "", title: "", subtitle: "", group: "General", sections: [] },
    fields: [
      { key: "slug", label: "Slug", type: "string" },
      { key: "title", label: "Page title", type: "string" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "group", label: "Group", type: "string" },
      { key: "heroImage", label: "Hero image", type: "image" },
      { key: "sections", label: "Sections JSON", type: "json" },
    ],
  },
};

export function getCollection(key: string) {
  return COLLECTIONS[key];
}

export function allCollections() {
  return Object.values(COLLECTIONS);
}
